import { NextResponse } from "next/server"

// Mock employee data (shared with other APIs)
const employees = [
  {
    id: "101",
    full_name: "John Doe",
    new_position: "Senior Loan Officer",
    department: "Loans",
    branch: "Main Branch",
    district: "Central",
    individual_pms: "85",
    indpms25: "21.25",
    totalexp: "8",
    totalexp20: "16",
    tmdrec20: "18",
    disrec15: "",
    total_score: "",
    status: "active",
  },
  {
    id: "102",
    full_name: "Jane Smith",
    new_position: "Customer Service Manager",
    department: "Customer Service",
    branch: "Downtown Branch",
    district: "East",
    individual_pms: "90",
    indpms25: "22.5",
    totalexp: "6",
    totalexp20: "12",
    tmdrec20: "17",
    disrec15: "",
    total_score: "",
    status: "active",
  },
  {
    id: "103",
    full_name: "Michael Johnson",
    new_position: "IT Manager",
    department: "IT",
    branch: "Tech Branch",
    district: "West",
    individual_pms: "88",
    indpms25: "22",
    totalexp: "10",
    totalexp20: "18",
    tmdrec20: "",
    disrec15: "",
    total_score: "",
    status: "active",
  },
  {
    id: "104",
    full_name: "Sarah Williams",
    new_position: "Teller Supervisor",
    department: "Operations",
    branch: "North Branch",
    district: "North",
    individual_pms: "82",
    indpms25: "20.5",
    totalexp: "5",
    totalexp20: "10",
    tmdrec20: "",
    disrec15: "",
    total_score: "",
    status: "active",
  },
  {
    id: "105",
    full_name: "Robert Brown",
    new_position: "Branch Manager",
    department: "Management",
    branch: "South Branch",
    district: "South",
    individual_pms: "92",
    indpms25: "23",
    totalexp: "12",
    totalexp20: "19",
    tmdrec20: "",
    disrec15: "",
    total_score: "",
    status: "active",
  },
]

// GET /api/employees
export async function GET() {
  return NextResponse.json(employees)
}
