export interface Employee {
  id: string
  file_number: string
  full_name: string
  sex?: string
  job_grade?: string
  job_category?: string
  branch?: string
  department?: string
  district?: string
  region?: string
  educational_level?: string
  field_of_study?: string
  new_position?: string
  current_position?: string
  employment_date?: string
  last_dop?: string
  new_salary?: string
  indpms25?: number
  totalexp?: number
  totalexp20?: number
  relatedexp?: number
  expafterpromo?: number
  tmdrec20?: number
  disrec15?: number
  total?: number
  individual_pms?: number
  twin_branch?: string
  cluster?: string
}
